twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_5_layout.html.twig']

=======
    form_themes: ['bootstrap_4_layout.html.twig']
>>>>>>> d52008ea3b4817606005e07e0b14b6d9966dc876

when@test:
    twig:
        strict_variables: true
