# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: false
            delete_on_update: false
        club_logo:
            uri_prefix: '%app.path.club_logo%'
            upload_destination: '%kernel.project_dir%/public%app.path.club_logo%'